const NoteCollectionCRUDActionTypes = {
  SELECT_NOTE_COLLECTION: "SELECT_NOTE_COLLECTION",

  NOTE_COLLECTION_CRUD_CANCEL: "NOTE_COLLECTION_CRUD_CANCEL",

  ADD_NOTE_COLLECTION_START: "ADD_NOTE_COLLECTION_START",
  ADD_NOTE_COLLECTION_SEND_REQUEST: "ADD_NOTE_COLLECTION_SEND_REQUEST",
  ADD_NOTE_COLLECTION_SUCCESS: "ADD_NOTE_COLLECTION_SUCCESS",
  ADD_NOTE_COLLECTION_FAILURE: "ADD_NOTE_COLLECTION_FAILURE",

  EDIT_NOTE_COLLECTION_START: "EDIT_NOTE_COLLECTION_START",
  EDIT_NOTE_COLLECTION_SEND_REQUEST: "EDIT_NOTE_COLLECTION_SEND_REQUEST",
  EDIT_NOTE_COLLECTION_SUCCESS: "EDIT_NOTE_COLLECTION_SUCCESS",
  EDIT_NOTE_COLLECTION_FAILURE: "EDIT_NOTE_COLLECTION_FAILURE",

  DELETE_NOTE_COLLECTION_SEND_REQUEST: "DELETE_NOTE_COLLECTION_SEND_REQUEST",
  // DELETE_NOTE_COLLECTION_SUCCESS: "DELETE_NOTE_COLLECTION_SUCCESS",
  DELETE_NOTE_COLLECTION_FAILURE: "DELETE_NOTE_COLLECTION_FAILURE",

  PIN_SELECTED_NOTE_COLLECTION: "PIN_SELECTED_NOTE_COLLECTION",
  UNPIN_SELECTED_NOTE_COLLECTION: "UNPIN_SELECTED_NOTE_COLLECTION",
  PIN_NOTE_COLLECTION_FAILURE: "PIN_NOTE_COLLECTION_FAILURE",
};

export default NoteCollectionCRUDActionTypes;
