const NotesActionTypes = {
  FETCH_NOTES_START: "FETCH_NOTES_START",
  FETCH_NOTES_SUCCESS: "FETCH_NOTES_SUCCESS",
  FETCH_NOTES_FAILURE: "FETCH_NOTES_FAILURE",

  // SELECT_NOTE: "SELECT_NOTE",
  ADD_NOTE_START: "ADD_NOTE_START",
  ADD_NOTE_REQUEST: "ADD_NOTE_REQUEST",
  ADD_NOTE_SUCCESS: "ADD_NOTE_SUCCESS",
  ADD_NOTE_FAILURE: "ADD_NOTE_FAILURE",

  UPDATE_NOTE_START: "UPDATE_NOTE_START",
  UPDATE_NOTE_REQUEST: "UPDATE_NOTE_REQUEST",
  UPDATE_NOTE_SUCCESS: "UPDATE_NOTE_SUCCESS",
  UPDATE_NOTE_FAILURE: "UPDATE_NOTE_FAILURE",

  DELETE_NOTE_REQUEST: "DELETE_NOTE_REQUEST",
  DELETE_NOTE_SUCCESS: "DELETE_NOTE_SUCCESS",
  DELETE_NOTE_FAILURE: "DELETE_NOTE_FAILURE",

  CANCEL_NOTE: "CANCEL_NOTE",
};

export default NotesActionTypes;
