const NoteCollectionsActions = {
  FETCH_NOTE_COLLECTIONS_START: "FETCH_NOTE_COLLECTIONS_START",
  FETCH_NOTE_COLLECTIONS_SUCCESS: "FETCH_NOTE_COLLECTIONS_SUCCESS",
  FETCH_NOTE_COLLECTIONS_FAILURE: "FETCH_NOTE_COLLECTIONS_FAILURE",

  INSERT_NOTE_COLLECTION: "INSERT_NOTE_COLLECTION",
  UPDATE_NOTE_COLLECTION: "UPDATE_NOTE_COLLECTION",
  DELETE_NOTE_COLLECTION: "DELETE_NOTE_COLLECTION",
};

export default NoteCollectionsActions;
